### ISSUE TITLE
QoL Feature Requests

### ISSUE THREAD

**Issue by Tinkerlad0** [JarrahGos/TOC19#49]
When modifying things such as Stock counts and person/admin details you must press 'enter' to submit the changes. Potentially it may be worth adding a method of feedback that indicates that the operation has completed successfully.

I am looking at submitting a PR soon with an example feature of how I would accomplish this (either briefly highlight the TB green or make a tick next to the TB)

**Comment by JarrahGos** [comment]
Sounds like a great idea. I had been looking at adding a button which would do this as well, but I think I prefer the highlight. 

Would it still swap to the next product or person when this occurs? That is something that makes a huge difference to usability, especially in the stock counts. 

Also, ensure you pull before changing the code. Otherwise there will be a hell of a merge at the end.

**Comment by Tinkerlad0** [comment]
The functionality of the system should remain exactly the same, what I aim to do is change the background colour of the TextField to a nice shade of green then have it slowly fade back to the original colour. The idea is that it will be a separate method(s) that will apply the effect to a variety of controls as necessary to enable easily adopting it for other uses. 

At the moment I am trying to get my head around JavaFX a little more, I want to use its animation abilities hopefully. However failing that a may just revert back to a timer to accomplish the fade back to original colour.

**Comment by Tinkerlad0** [comment]
Completed in #53
